trigger:
  branches:
    include: ["master", "develop*", "release*", "refs/tags/*" ]
  paths:
    exclude: [ "doc", "*.md", ".gitignore" ]

jobs:
- job: Building_Toolkit
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      pip install gdown
      gdown --fuzzy https://drive.google.com/u/0/uc?id=1Dg5BZtatClyEX0zPYXjYKiNGHGMkbQ4G&export=download
      ren *.zip wxWidgets.zip
      7z x wxWidgets.zip -oD:/
      dir
      cd D:/
      dir
    displayName: Download wxWidgets
    
  - task: VSBuild@1
    displayName: Build VSCode Tools
    env:
      WXWIN: D:/wxWidgets/
    inputs:
      configuration: 'release'
      solution: '**\*.sln' 
      vsVersion: '16.0' # Optional. Options: latest, 16.0, 15.0, 14.0, 12.0, 11.0
      msbuildArchitecture: 'x86' # Optional. Options: x86, x64
      
  - script: |
      cd Tools
      cd NRDC
      makeme.bat
    displayName: Build GCC Tools
      
  - script: |
      cd Tools
      mkdir ToolsRelease
      for /r . %%x in (*.exe) do copy "%%x" "ToolsRelease"
      cd ToolsRelease
      dir
      del /q /f bin2c.exe
    displayName: Move Executables
    
  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifacts
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/Tools/ToolsRelease/'
      artifactName: 'tools-windows'
